widgets:
  network-tiles-stack:
    type: network
    name: "Network: Tiles Stacked"
    log_file: network.log
    federation:
      merge: [nas-1, nas-2]
      display:
        tiles: stack
    show:
      tiles: true
      uptime: false
      outages: false

  wiki-network-tiles-stack:
    type: wiki
    name: "Config: Tiles Stacked"
    style: seamless
    doc: docs/multi/network/tiles/stack.md
