widgets:
  services-stack:
    type: services
    name: "Services: Stacked"
    federation:
      merge: [nas-1, nas-2]
      display:
        cards: stack

  wiki-services-stack:
    type: wiki
    name: "Config: Services Stacked"
    _suppressHeader: true
    mode: seamless
    doc: ../../../docs/multi/services/stack.md
