---
demo: true
site:
  name: '@editor'
  title: monitor@editor
includes:
  - ../simple/snippets/wiki.yaml
  - ../simple/snippets/footer.yaml
paths:
  data: ../simple/data/
  img: ../simple/img/
  favicon: ../simple/img/favicon.svg
  vendors: ../simple/vendors/
widgets:
  enabled:
    - editor-readme
    - dummy
    - wiki-footer
  # - reminders

  editor-readme:
    type: wiki
    _suppressHeader: true
    doc: docs/README.md
    mode: seamless
    edit: true
    collapsible: false
    edit: false

  dummy:
    type: wiki
    name: Dummy Document
    doc: docs/dummy.md
    mode: rail
    collapsible: true
    edit: true

  wiki-footer:
    type: wiki
    name: Links
    hidden: true
    mode: seamless
    doc: docs/footer.md
    edit: false
