---
demo: true
site:
  name: '@editor'
  title: monitor@editor
includes:
  - ../simple/snippets/wiki.yaml
  - ../simple/snippets/footer.yaml
paths:
  data: ../simple/data/
  img: ../simple/img/
  favicon: ../simple/img/favicon.svg
  vendors: ../../vendors/
sections:
  editor-readme:
    title: null
    collapsible: false
  dummy:
    title: Dummy Document
  wiki-footer:
    title: Links

widgets:
  enabled:
    - editor-readme
    - dummy
    - wiki-footer
  # - reminders

  editor-readme:
    type: wiki
    name: null
    section: editor-readme
    doc: ./README.md
    mode: seamless
    edit: true
    edit: false

  dummy:
    type: wiki
    name: null
    section: dummy
    doc: docs/dummy.md
    mode: rail
    edit: true

  wiki-footer:
    type: wiki
    name: null
    section: wiki-footer
    hidden: true
    mode: seamless
    doc: ../simple/docs/footer.md
    edit: false
