---
widgets:
  services:
    name: Services
    collapsible: true
    hidden: false
    items:
      monitor:
        name: monitor@
        icon: favicon.svg
        services: [monitor@demo.service]
      ollama:
        name: Ollama
        icon: services/systemd/ollama.svg
        services: [ollama.service]
      plex_letterboxd:
        name: Plex Letterboxd
        icon: services/systemd/letterboxd.png
        services: [plex-letterboxd@demo.service]
        timers: [plex-letterboxd@demo.timer, plex-letterboxd@monthly.timer]
      jellyfin:
        name: Jellyfin
        icon: services/docker/jellyfin.png
        containers: [jellyfin]
        url: https://example.com/jellyfin/
        local: http://demo-host:8096/jellyfin
      immich:
        name: Immich
        icon: services/docker/immich.webp
        containers:
          - immich_server
          - immich_machine_learning
          - immich_microservices
          - immich_postgres
          - immich_redis
        url: https://photos.example.com/
        local: http://demo-host:2283
      plex:
        name: Plex
        icon: services/systemd/plex.png
        services: [plexmediaserver.service]
        url: https://example.com/plex
        local: http://demo-host:32400
      syncthing:
        name: Syncthing
        icon: services/systemd/syncthing.png
        services: [syncthing@demo.service]
        url: https://example.com/syncthing
        local: http://demo-host:8384
      kometa:
        name: Kometa
        icon: services/systemd/kometa.png
        timers: [kometa@full.timer, kometa@recent.timer]
        url: https://example.com/plex
        local: http://demo-host:32400
      tinybeans:
        name: Tinybeans Sync
        icon: services/systemd/tinybeans.png
        timers: [tinybeans-sync.timer]
        url: https://example.com
        local: https://photos.example.com
      miniflux:
        name: Miniflux
        icon: services/docker/miniflux.png
        containers: [miniflux]
        url: https://rss.example.com
        local: http://demo-host:1221
      porkbun_ddns:
        name: Porkbun DDNS
        icon: services/systemd/porkbun.png
        timers: [porkbun-ddns.timer]
      nginx:
        name: Nginx
        icon: services/systemd/nginx.png
        services: [nginx.service]
