widgets:
  metrics-tiles-stack:
    type: metrics
    name: "Metrics: Tiles Stacked"
    collapsible: true
    federation:
      nodes: [nas-1, nas-2]
      display:
        tiles: stack
    show:
      tiles: true
      history: false

  wiki-metrics-tiles-stack:
    type: wiki
    name: "Config: Tiles Stacked"
    parent: metrics-tiles-stack
    _suppressHeader: true
    mode: rail
    doc: ../../../docs/metrics/tiles/stack.md
