widgets:
  services-merge:
    type: services
    name: "Services: Merged"
    collapsible: true
    federation:
      nodes: [nas-1, nas-2]

  wiki-services-merge:
    type: wiki
    name: "Config: Services Merged"
    parent: services-merge
    _suppressHeader: true
    mode: rail
    doc: ../../docs/combinators/services.md
