---
# minimal monitor@ configuration that renders a simple dashboard.
includes:
  # TODO: eventually load snippets dynamically
  - widgets/metrics/config_default.yaml
  - widgets/services/config_default.yaml
  - widgets/reminders/config_default.yaml
  - widgets/speedtest/config_default.yaml
  - widgets/network/config_default.yaml
  - widgets/wiki/config_default.yaml
site:
  name: monitor@
  title: System Monitor
  base_url: http://localhost:6161
# all paths relative to monitor@ config dir (~/.config/monitor@/)
# absolute paths also supported
paths:
  data: data/
  img: img/
  favicon: favicon.ico
  vendors: vendors/
  widgets: [widgets/]
notifications:
  apprise_urls: []
auth:
  api_key: ''
federation:
  enabled: false
  timeout_seconds: 10
  remotes: []
demo: false
widgets:
  enabled:  # provides order and visibility
    - metrics  # monitorat/widgets/* for available widgets
    - speedtest
    - wiki
privacy:  # toggle, for screenshots
  mask_ips: true
  replacements: {}  # { my-site.com: example.com ; ... }
