widgets:
  services-single:
    type: services
    name: "Services"
    remote: nas-1

  wiki-services-single:
    type: wiki
    name: "Config: Services"
    style: seamless
    doc: ../../../docs/single/widgets/services.md
