widgets:
  wiki-stack:
    type: wiki
    name: "All Wikis (Stacked)"
    doc: true
    federation:
      merge: [nas-1, nas-2]
      display:
        document: stack

  wiki-stack-doc:
    type: wiki
    name: "Config: Stack"
    style: seamless
    doc: docs/multi/wiki/stack.md
