widgets:
  reminders:  # uses top-level notification settings
    name: Reminders
    collapsible: true
    hidden: false
    min_width: 260px
    edit_file: null  # relative to config dir, or absolute
    features:
      reminders:
        header: null
    state_file: reminders.json  # relative to data path, or absolute
    nudges: ["14 days", "7 days"]
    urgents: ["3 days", "1 day", "0 days"]
    time: "23:55"  # what time to check
    items: {}  # { protonmail: {} ; GitHub SSH Keys: {} ; ... }
