widgets:
  services-stack:
    type: services
    name: "Services: Stacked"
    collapsible: true
    federation:
      nodes: [nas-1, nas-2]
      display:
        cards: stack

  wiki-services-stack:
    type: wiki
    name: "Config: Services Stacked"
    parent: services-stack
    _suppressHeader: true
    mode: rail
    doc: ../../docs/services/stack.md
