---
demo: true
site:
  name: '@demo'
  title: monitor@demo
includes:
  - snippets/metrics.yaml
  - snippets/network.yaml
  - snippets/services.yaml
  - snippets/speedtest.yaml
  - snippets/reminders.yaml
  - snippets/wiki.yaml
  - snippets/quick-links.yaml
paths:
  data: data/
  img: img/
  favicon: img/favicon.svg
widgets:
  enabled:
    - wiki
    - metrics
    - metrics-md
    - network
    - network-md
    - services
    - services-md
    - speedtest
    - speedtest-md
    - reminders
    - reminders-md
    - wiki-quick-links
  metrics-md:
    type: wiki
    mode: rail
    name: Metrics Notes
    enabled: true
    doc: ./docs/metrics.md
    _suppressHeader: true
  network-md:
    type: wiki
    mode: rail
    name: Network Notes
    enabled: true
    doc: ./docs/network.md
    _suppressHeader: true
  services-md:
    type: wiki
    mode: rail
    name: Services Notes
    enabled: true
    doc: ./docs/services.md
    _suppressHeader: true
  speedtest-md:
    type: wiki
    mode: rail
    name: Speedtest Notes
    enabled: true
    doc: ./docs/speedtest.md
    _suppressHeader: true
  reminders-md:
    type: wiki
    mode: rail
    name: Reminders Notes
    enabled: true
    doc: ./docs/reminders.md
    _suppressHeader: true
