widgets:
  network-uptime-stack:
    type: network
    name: "Network: Uptime Stacked"
    log_file: network.log
    federation:
      merge: [nas-1, nas-2]
      display:
        uptime: stack
    show:
      tiles: false
      uptime: true
      outages: false
    uptime:
      show: true
      periods:
        - period: 1 hour
          segment_size: 5 minutes

  wiki-network-uptime-stack:
    type: wiki
    name: "Config: Uptime Stacked"
    style: seamless
    doc: ../../../../docs/multi/network/uptime/stack.md
