widgets:
  metrics-tiles-stack:
    type: metrics
    name: "Metrics: Tiles Stacked"
    federation:
      merge: [nas-1, nas-2]
      display:
        tiles: stack
    show:
      tiles: true
      history: false

  wiki-metrics-tiles-stack:
    type: wiki
    name: "Config: Tiles Stacked"
    _suppressHeader: true
    mode: seamless
    doc: ../../../../docs/multi/metrics/tiles/stack.md
