widgets:
  reminders-stack:
    type: reminders
    name: "Reminders: Stacked"
    federation:
      merge: [nas-1, nas-2]
      display:
        cards: stack

  wiki-reminders-stack:
    type: wiki
    name: "Config: Reminders Stacked"
    _suppressHeader: true
    mode: seamless
    doc: ../../../docs/multi/reminders/stack.md
